import React from 'react';
import './style.scss';

function WallPaperPreview() {
  return <div className="wallpaperpreview-wrapper">WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
    <br/>WallPaperPreview
  </div>;
}

export default WallPaperPreview;
